language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

# command to install dependencies
install:
    - make init

# command to run tests
script:
    - make test

# run codecov
after_success:
    - bash <(curl -s https://codecov.io/bash)

branches:
  only:
    - master
